### ISSUE TITLE
Get better refreshRate precision

### ISSUE THREAD

**Issue by yoyos** [falahati/EDIDParser#2]
Hello,

How could I get available timings with EDIDParser in milliseconds like my computer and NvApiWrapper ?

For same resolution, same display:

* EDIDParser gives me 60 

![image](https://user-images.githubusercontent.com/1993859/197172899-487707fe-1352-4b20-ab95-270672ea1d46.png)

* But my computer 

![image](https://user-images.githubusercontent.com/1993859/197173200-241d4e0d-5222-4b44-a876-7c9da8612ad1.png)

* And NvApiWrapper 59950 too

![image](https://user-images.githubusercontent.com/1993859/197174397-39d0b56b-d10d-4100-94df-f342c27fad36.png)

**Comment by falahati** [comment]
EDID is old and limited. Common timing only contains a list of possible refresh rates and sizes, the standard timing table includes more detailed information, but still, the refresh rate is always an integer which means no 59.95 or 59.885. These numbers are then deduced by the driver when generating the expected signal. That's why NVidia and windows know about the real number but here we don't.

However, there is also a new table for detailed timings. This table does not in fact contain the refresh rate, but it has all the info required to calculate the actual refresh rate. All you have to do is to apply this formula:
```
RefreshRate = PixelClock / ((HorizontalActivePixels + HorizontalBlankingPixels + HorizontalBorderPixels) * (VerticalActivePixels + VerticalBlankingPixels + VerticalBorderPixels))
```

**Comment by falahati** [comment]
for 1920x1200 in your example it is:
```
(154,000,000 / ((1,920 + 160 + 0) * (1,200 + 35 + 0))) = 59.95017128620367
```

**Comment by falahati** [comment]
read this for more info:
https://glenwing.github.io/docs/VESA-DMT-1.13.pdf

**Comment by falahati** [comment]
and here contains a more detailed formula:
https://electronics.stackexchange.com/questions/14828/how-do-i-calculate-needed-pixel-clock-frequency

should give you a better value.

**Comment by yoyos** [comment]
Thanks for the details :)

Yes I already processed the refreshrate with information coming from DetailedTimingDescriptor

It's works pretty well and I could build the same list of available resolutions as I can find in windows

Have a nice day !
