### ISSUE TITLE
Inconsistency between resolutions

### ISSUE THREAD

**Issue by yoyos** [falahati/EDIDParser#3]
![image](https://user-images.githubusercontent.com/1993859/197193118-75e710d9-183a-4fd9-ab99-bc0d457aa222.png)

Screens have not same available resolutions on Windows/Nvidia control panel as EDIDParser:

* My Iiyama
![image](https://user-images.githubusercontent.com/1993859/197192799-b481bffb-2288-4086-9756-1509471d01ac.png)
![image](https://user-images.githubusercontent.com/1993859/197192894-2b20cb94-17b1-4af7-8ec3-e56b9a84c994.png)
![image](https://user-images.githubusercontent.com/1993859/197193076-4a0205b9-9657-4236-9bfb-0e8cd6c03e70.png)

* My DELL
![image](https://user-images.githubusercontent.com/1993859/197192143-de4a31a0-5d83-4570-a12f-292cbbf837f0.png)
![image](https://user-images.githubusercontent.com/1993859/197192244-49a0f7bb-19cf-456a-95e5-b5f1cdc2a825.png)
![image](https://user-images.githubusercontent.com/1993859/197192595-6f23f94f-c4c4-48d8-9a60-9af3f58a6393.png)

**Comment by yoyos** [comment]
I could access hidden resolutions in DetailedTimingDescriptor
But first I had to remove throwing errors that were in my way with issue #4 

![image](https://user-images.githubusercontent.com/1993859/197220610-a7ccfc57-43a9-4cec-bd69-26b10bf81a5f.png)

**Comment by falahati** [comment]
1. EDID shows the list of supported resolutions by the display
2. NVidia control panel shows the list of supported resolutions by the display, filtered by the supported outputs of the GPU. and might also include custom resolutions added directly and forced by the driver
3. Windows shows the list of supported resolutions reported by the GPU's driver.

There is no guarantee for these three lists to be identical.

as for the exceptions. you must handle them on your own program. The `EDIDParseSample` project is just there to show you what values to expect and how the library works. Otherwise, you must install the library by nuget and write your own code, then you can handle the exceptions gracefully. No need to modify the library.

**Comment by yoyos** [comment]
Thanks I'll try that !
